argmin-rs/argmin

.circleci/config.yml, src/solver/simulatedannealing/mod.rs
Add a CircleCI config that runs,
- `cargo fmt`
- `cargo clippy`: failures are allowed, and one would need to actually look at the logs to see warnings / errors there.
=> MAINT Lint with CircleCI

Cargo.toml, src/lib.rs, src/tests.rs
Add a few unit tests that check convergence, adapted from [scipy.optimize.tests.test_optimize](https://github.com/scipy/scipy/blob/8e40c067b64016dc344c537655f56454fd1788ba/scipy/optimize/tests/test_optimize.py#L51).
The following tests were added,
```
test tests::test_max_entropy_bfgs ... ok
test tests::test_max_entropy_lbfgs_hagerzhang ... ok
test tests::test_max_entropy_dfp ... ok
test tests::test_max_entropy_newton_cg ... ok
test tests::test_max_entropy_lbfgs_morethuente ... ok
test tests::test_max_entropy_steepest_descent ... ok
```
so not all optimizer are for now included.
I have put these tests in `src/tests.rs` not sure if it's the best location. Maybe `src/solvers/tests.rs`? The idea was keep these in one place since they are "common tests" and then solver specific tests could go …
=> Add unit tests to check convergence on the Max Entropy problem

src/macros.rs, src/solver/conjugategradient/beta.rs, src/solver/conjugategradient/cg.rs, src/solver/conjugategradient/nonlinear_cg.rs, src/solver/gaussnewton/gaussnewton_linesearch.rs, src/solver/gaussnewton/gaussnewton_method.rs, src/solver/gradientdescent/steepestdescent.rs, src/solver/landweber/mod.rs, src/solver/linesearch/backtracking.rs, src/solver/linesearch/condition.rs, src/solver/linesearch/hagerzhang.rs, src/solver/linesearch/morethuente.rs, src/solver/neldermead/mod.rs, src/solver/newton/newton_cg.rs, src/solver/newton/newton_method.rs, src/solver/particleswarm/mod.rs, src/solver/quasinewton/bfgs.rs, src/solver/quasinewton/dfp.rs, src/solver/quasinewton/lbfgs.rs, src/solver/quasinewton/sr1.rs, src/solver/quasinewton/sr1_trustregion.rs, src/solver/simulatedannealing/mod.rs, src/solver/trustregion/cauchypoint.rs, src/solver/trustregion/dogleg.rs, src/solver/trustregion/steihaug.rs, src/solver/trustregion/trustregion_method.rs
Makes sure all optimizer derive the `Clone` trait.
The only exception is `ParticleSwarm` because it sounds like `Callback<T>` does not implement `Clone` and I have not investigated further.
Something I have run into in `pyargmin` when changing solvers.
Helps toward "Interoperability" in https://github.com/argmin-rs/argmin/issues/1
=> Derive Clone trait for all optimizers

src/core/mod.rs, src/core/observers/mod.rs
This removes the `Send` and `Sync` trait bounds from `ArgminOp` (for now).
=> Removed Send and Sync trait bounds from ArgminOp

Cargo.toml, src/core/math/mod.rs
Reexporting the `modcholesky` crate is not necessary.
=> No reexport of modcholesky crate

src/solver/quasinewton/lbfgs.rs
This PR makes the tolerances in the stopping criterion of L-BFGS accessible to the user (see #28). 
@rth, is this how you imagined it? I would appreciate it if you could give this a quick review.
=> Exposed stopping criterion tolerances to user

.gitignore, src/solver/newton/newton_cg.rs
This exposes the stopping criterion tolerances of `NewtonCG` to the user. Related to #28.
=> Exposed stopping criterion tolerance of NewtonCG method to user

src/solver/quasinewton/bfgs.rs, src/solver/quasinewton/dfp.rs, src/solver/quasinewton/sr1.rs, src/solver/quasinewton/sr1_trustregion.rs
This exposes the stopping criterion tolerances of the Quasi-Newton methods to the user. Related to #28.
=> Exposed stopping criterion tolerances of Quasi-Newton methods to user

Cargo.toml, examples/backtracking.rs, examples/bfgs.rs, examples/checkpoint_3.rs, examples/dfp.rs, examples/hagerzhang.rs, examples/landweber.rs, examples/lbfgs.rs, examples/morethuente.rs, examples/neldermead.rs, examples/newton.rs, examples/newton_cg.rs, examples/nonlinear_cg.rs, examples/particleswarm.rs, examples/simulatedannealing.rs, examples/sr1.rs, examples/sr1_trustregion.rs, examples/steepestdescent.rs, examples/trustregion_nd.rs, examples/writers.rs, src/core/result.rs, src/lib.rs
`argmin_testfunctions` is not reexported anymore. This avoids version inconsistencies and it avoids having to bump the `argmin` version whenever a new version of `argmin_testfunctions` is released.
=> No reexport of `argmin_testfunctions`

src/core/iterstate.rs
Fixes linter warnings and correctly documents getter and setter methods in `IterState`.
=> Fixed macro documentation in IterState

src/solver/linesearch/morethuente.rs
Added a check for NaN or Inf in the cstep calculation of the MoreThuente linesearch using iter any. Returns an error if an invalid value is encountered.
Should resolve issue #42
=> MoreThuente: Added error check for NaN or Inf

Cargo.toml
Without this change, `ndarrayl` feature not working.
`finitediff` is not used in code under the `ndarray` feature
=> remove `finitediff` from `ndarrayl` feature

Cargo.toml, README.md, examples/gaussnewton_nalgebra.rs, src/core/math/add_nalgebra.rs, src/core/math/conj_nalgebra.rs, src/core/math/div_nalgebra.rs, src/core/math/dot_nalgebra.rs, src/core/math/eye_nalgebra.rs, src/core/math/inv_nalgebra.rs, src/core/math/mod.rs, src/core/math/mul_nalgebra.rs, src/core/math/norm_nalgebra.rs, src/core/math/scaledadd_nalgebra.rs, src/core/math/scaledsub_nalgebra.rs, src/core/math/sub_nalgebra.rs, src/core/math/transpose.rs, src/core/math/transpose_nalgebra.rs, src/core/math/transpose_ndarray.rs, src/core/math/transpose_vec.rs, src/core/math/weighteddot.rs, src/core/math/zero_nalgebra.rs, src/solver/gaussnewton/gaussnewton_linesearch.rs, src/solver/gaussnewton/gaussnewton_method.rs, src/solver/quasinewton/bfgs.rs, src/solver/quasinewton/dfp.rs
This PR adds support for the [`nalgebra`](https://nalgebra.org) crate. This allows using static matrices with `argmin`. It also means that operations that panicked before now result in a compilation error (e.g., multiplying incompatible static matrices). 
Not all math traits were implemented; only the ones that were implemented for `ndarray` are now implemented for `nalgebra`. A usage example was also added for the Gauss-Newton solver.
The implementations of `argmin`'s math traits use a lof of generic code to support all the matrices provided by `nalgebra` (both static and dynamic ones). However, the disadvantage is that any change in `nalgabra`'s definitions of matrices or the functions they support will break the implementations in `argmin`.
NB: Thank you for providing and maintaining …
=> Add nalgebra support

src/solver/linesearch/backtracking.rs, src/solver/linesearch/hagerzhang.rs, src/solver/linesearch/morethuente.rs
The Backtracking and Hager Zhang line searches always evaluated the gradient, even if it was already present (because of usage of `unwrap_or`). In addition, More Thuente would panic if the gradient computation returns an error (because of usage of `unwrap`). This PR fixes this.
Unrelated: With respect to your usage of dependabot I would recommend using squash & merge in the Github UI to avoid littering your commit history with tons of merge commits. But feel free to ignore this opinion.
=> Fix lazy evaluation of gradients in line searches

src/solver/particleswarm/mod.rs, src/solver/quasinewton/bfgs.rs, src/solver/quasinewton/dfp.rs, src/solver/quasinewton/sr1.rs, src/solver/quasinewton/sr1_trustregion.rs
The latest nightly compilers require type annotations. It was necessary to replace one type with another (equivalent) type. Not sure why though...
Fixes #104 .
=> Fixed error when using recent nightly compiler 

Cargo.toml, README.md, src/lib.rs
=> downgrade ndarray-rand to 0.13 (to match ndarray 0.14), version bump

examples/backtracking.rs, examples/bfgs.rs, examples/brent.rs, examples/checkpoint_3.rs, examples/conjugategradient.rs, examples/dfp.rs, examples/gaussnewton.rs, examples/gaussnewton_linesearch.rs, examples/goldensectionsearch.rs, examples/hagerzhang.rs, examples/landweber.rs, examples/lbfgs.rs, examples/morethuente.rs, examples/neldermead.rs, examples/newton.rs, examples/newton_cg.rs, examples/nonlinear_cg.rs, examples/particleswarm.rs, examples/simulatedannealing.rs, examples/sr1.rs, examples/sr1_trustregion.rs, examples/steepestdescent.rs, examples/trustregion_nd.rs, examples/writers.rs
`extern crate <crate>` was removed in Rust a while ago, but as far as I remember it was still necessary in examples. Apparently examples now work without it, therefore it is better to remove it as it may cause problems when used in actual projects (#115).
=> Remove extern crate definitions from examples

Cargo.toml, src/core/math/add_nalgebra.rs, src/core/math/conj_nalgebra.rs, src/core/math/div_nalgebra.rs, src/core/math/dot_nalgebra.rs, src/core/math/eye_nalgebra.rs, src/core/math/inv_nalgebra.rs, src/core/math/mul_nalgebra.rs, src/core/math/sub_nalgebra.rs, src/core/math/transpose_nalgebra.rs, src/core/math/zero_nalgebra.rs
- Switched to `OMatrix` for the the NAlgebra implementation of the math traits. This will work with both static and dynamic matrices. I confirmed that these work even with `SMatrix`.
- Bumped NAlgebra to the latest released version
=> Squash warnings for Nalgebra 0.26.x

Cargo.toml, examples/sr1_trustregion.rs, src/core/iterstate.rs, src/core/observers/mod.rs
See the two commits provided for more context. 
The main crux of this is that I want to use `argmin`, but I don't want to include `slog` in the process. It makes sense then to make it a feature. Given how prolific this feature is throughout the library (it is the default terminal logger, even the file logger just goes to bincode / JSON), I opted to leave it as a default feature. Of course, if users don't want `slog` themselves, then they just have to specify the following in their `Cargo.toml`:
```TOML
[dependencies.argmin]
version = "0.4"
default-features = false
features = ["nalgebral", "ndarrayl"]
```
With whatever features they do want enabled explicitly in the `dependencies.argmin.features` array.
The first commit just cleaned up a bunch of clippy lints. The command I'm using is: …
=> Make use of `slog` a feature

Cargo.toml, examples/simulatedannealing.rs, src/solver/simulatedannealing/mod.rs
Resolves #138.
The old example was overwriting previous `param_n` iterations so I fixed that.
`Rosenbrock` in the example could also allow any RNG if we remove the `Default` implementation.
=> allow any RNG, improve SA example

src/core/macros.rs
This produces a warning in rustc 1.56.1
=> Remove unnecessary semi-colon in macro

CHANGELOG.md, src/solver/simulatedannealing/mod.rs
This addresses #150 
It appears to me that the initial `ArgminIterData` returned by the simulated anneal solver's `init` method does not contain values for `param` and `cost`. Hence the `executor`'s state is not being updated upon calling the `solver`'s `init` method. This leads to the state having infinity as starting cost, which makes any first solution preferable.
I have added param and corresponding initial cost to the solver's init method.
=> [fix] simulated anneal always accepts first iter

src/core/executor.rs, src/core/opwrapper.rs, src/core/result.rs, src/solver/conjugategradient/nonlinear_cg.rs, src/solver/gaussnewton/gaussnewton_linesearch.rs, src/solver/gradientdescent/steepestdescent.rs, src/solver/newton/newton_cg.rs, src/solver/quasinewton/bfgs.rs, src/solver/quasinewton/dfp.rs, src/solver/quasinewton/lbfgs.rs, src/solver/quasinewton/sr1.rs, src/solver/quasinewton/sr1_trustregion.rs, src/solver/trustregion/trustregion_method.rs, src/tests.rs
The function evaluation counts of sub problems were not correctly added to the function evaluation counts of the main solver. This was fixed by removing one unnecessary layer of `OpWrapper` when setting up subproblems. This allowed for simplifying the `OpWrapper` implementation as well.
Addresses #154
=> Fix counting of sub problem function counts

src/solver/linesearch/backtracking.rs, src/solver/linesearch/condition.rs
Currently the `LineSearchCondition` takes its vector arguments by value. Consequently, the line search always has to explicitly clone the gradient / search direction vectors. For larger systems this might be expensive, especially if many line search iterations are needed. I don't see a reason why an explicit clone should be enforced by the interface. Therefor, I would propose to change the trait to accept references.
=> Update LineSearchCondition trait to use references

src/solver/simulatedannealing/mod.rs
Fixes #157. Also, a solution is now only labelled as new best if it is strictly better than the previous best.
=> SA: use correct previous cost, new best needs to be strictly better

src/macros.rs, src/solver/linesearch/condition.rs
Tests for Armijo, Wolfe, StrongWolfe and Goldstein conditions. Fixed a bug in Goldstein conditions.
Also adds a macro to make testing for errors easier.
=> Tests for linesearch conditions

src/solver/linesearch/backtracking.rs
Adds tests for backtracking line search and furthermore removes unnecessary box around line search condition.
=> Tests for backtracking linesearch

README.md, src/lib.rs
When important features aren't mentioned, this can lead to [some confusion](https://github.com/dariogoetz/keyboard_layout_optimizer/pull/7#issuecomment-1001672035)
Therefore, I suggest quickly mentioning them. :)
This pull-request adds a mention about WebAssembly and the required features.
---
Eventually, it would be handy to have every existing feature described in the `Readme.md`. Nothing extensive, just a short mention that the feature exists and an overview of what it does.
=> Mention wasm-features in `Readme.md`

.github/workflows/ci.yml, Cargo.toml
This adds building for various WASM targets in the CI. Its likely far from perfect, but it should be able to catch a couple of things that could go wrong. 
Also includes changes which were necessary due to closing #148 and uses `netlib` instead of `openblas` in the tests (needed by `ndarray-linalg`) which hopefully fixes the problem that the CI regularly, but not always, crashes during compilation of `openblas`.
=> WASM builds in CI

.github/workflows/ci.yml
In the past there was a problem on Travis CI which (apparently) could be fixed by cleaning between build and test. Obviously this slows everything down. I assume this "fix" is not necessary anymore.
=> Faster CI by removing unnecessary `cargo clean`

src/solver/goldensectionsearch/mod.rs
The field `init_estimate` of the `GoldenSectionSearch` struct is apparently not used. The initial guess is actually taken from the `IterState`. 
This was apparently not caught by the compiler because `Serialize` and `Deserialize` are derived on it (which makes the field non-dead ;)).
=> Remove unused field in GoldenSectionSearch struct

argmin/src/core/mod.rs, argmin/src/solver/conjugategradient/beta.rs, argmin/src/solver/conjugategradient/cg.rs, argmin/src/solver/conjugategradient/nonlinear_cg.rs, argmin/src/solver/gaussnewton/gaussnewton_linesearch.rs, argmin/src/solver/gaussnewton/gaussnewton_method.rs, argmin/src/solver/gradientdescent/steepestdescent.rs, argmin/src/solver/linesearch/backtracking.rs, argmin/src/solver/linesearch/condition.rs, argmin/src/solver/linesearch/hagerzhang.rs, argmin/src/solver/linesearch/morethuente.rs, argmin/src/solver/neldermead/mod.rs, argmin/src/solver/newton/newton_cg.rs, argmin/src/solver/newton/newton_method.rs, argmin/src/solver/particleswarm/mod.rs, argmin/src/solver/quasinewton/bfgs.rs, argmin/src/solver/quasinewton/dfp.rs, argmin/src/solver/quasinewton/lbfgs.rs, argmin/src/solver/quasinewton/sr1.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs, argmin/src/solver/simulatedannealing/mod.rs, argmin/src/solver/trustregion/cauchypoint.rs, argmin/src/solver/trustregion/dogleg.rs, argmin/src/solver/trustregion/steihaug.rs, argmin/src/solver/trustregion/trustregion_method.rs
#187 has shown that a `Default` trait bound on `O::Param` or `O::Hessian` causes `ndarray` types to not work anymore. Parts of it were fixed in #192. In this PR I removed all remaining `Default` trait bounds and also cleaned up all other trait bounds.
=> Remove Default and other unnecessary trait bounds from solvers

argmin/src/solver/quasinewton/dfp.rs, argmin/src/solver/quasinewton/sr1.rs
When merging #186 somehow a problem was introduced. The Clone trait bound in DFP and SR1 got lost.
=> Hessian in DFP and SR1 needs to implement Clone

argmin/src/solver/quasinewton/bfgs.rs, argmin/src/solver/quasinewton/sr1.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs
By wrapping `init_inv_hessian` into an `Option`, we can `.take()` the content instead of needing to clone it in `init`.
=> Make `init_inv_hessian` in DFP and SR1 optional to avoid cloning

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, README.md, src/lib.rs
- Fixed Bug in HagerZhang line search (@wfsteiner)
- #2 
- #184 
- Removed Default trait bounds on TrustRegion and Steihaug implementations (@cfunky)
- #187 
- #192
- Inverse Hessians are now part of IterState, therefore the final inverse Hessian can be retrieved after an optimization run (@stefan-k)
- #185
- #186
=> version 0.5.1

argmin-math/src/nalgebra_m/dot.rs, argmin/examples/conjugategradient.rs, argmin/examples/nonlinear_cg.rs, argmin/src/core/errors.rs, argmin/src/core/mod.rs, argmin/src/core/state/iterstate.rs, argmin/src/solver/conjugategradient/beta.rs, argmin/src/solver/conjugategradient/cg.rs, argmin/src/solver/conjugategradient/mod.rs, argmin/src/solver/conjugategradient/nonlinear_cg.rs, argmin/src/solver/newton/newton_cg.rs
=> Cleanup and improve documentation of `ConjugateGradient` and `NonlinearConjugateGradient`

argmin/src/core/macros.rs, argmin/src/core/problem.rs, argmin/src/solver/conjugategradient/cg.rs, argmin/src/solver/conjugategradient/nonlinear_cg.rs, argmin/src/solver/gaussnewton/gaussnewton_linesearch.rs, argmin/src/solver/gaussnewton/gaussnewton_method.rs, argmin/src/solver/goldensectionsearch/mod.rs, argmin/src/solver/gradientdescent/steepestdescent.rs, argmin/src/solver/linesearch/backtracking.rs, argmin/src/solver/linesearch/condition.rs, argmin/src/solver/linesearch/hagerzhang.rs, argmin/src/solver/linesearch/morethuente.rs, argmin/src/solver/neldermead/mod.rs, argmin/src/solver/newton/newton_cg.rs, argmin/src/solver/newton/newton_method.rs, argmin/src/solver/quasinewton/sr1.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs, argmin/src/solver/simulatedannealing/mod.rs, argmin/src/solver/trustregion/dogleg.rs, argmin/src/solver/trustregion/steihaug.rs, argmin/src/solver/trustregion/trustregion_method.rs
This PR adds two macros `argmin_error!` and `argmin_error_closure!` which make it more convenient to create `ArgminError`s. 
The latter is meant to be used in `.ok_or_else(...)` methods of `Option`s.
=> `argmin_error!` and `argmin_error_closure!` macros for easier error creation

argmin/examples/neldermead.rs, argmin/src/solver/neldermead/mod.rs
=> Cleanup of NelderMead, documentation and doc and unit tests

argmin/src/core/errors.rs
Making the `ArgminError` enum `non_exhaustive` avoids that additions to the enum will be breaking changes. It forces downstream crates to add a wildcard arm to match expressions. 
Details: https://rust-lang.github.io/rfcs/2008-non-exhaustive.html
=> Made `ArgminError` non_exhaustive

README.md, argmin/src/core/checkpointing/mod.rs, argmin/src/lib.rs
Makes it more clear that not argmin is responsible for crashes but unstable environments. 
Also changes the default of `CheckpointingMode` from `Never` to `Always`, which makes more sense. 
Adapts the docs to the new code.
=> Improved documentation of checkpointing

argmin-math/src/ndarray_m/dot.rs, argmin-math/src/ndarray_m/inv.rs, argmin-math/src/primitives/dot.rs, argmin-math/src/vec/dot.rs, argmin/examples/bfgs.rs, argmin/examples/dfp.rs, argmin/examples/sr1.rs, argmin/examples/writers.rs, argmin/src/solver/conjugategradient/nonlinear_cg.rs, argmin/src/solver/gaussnewton/gaussnewton_linesearch.rs, argmin/src/solver/newton/newton_cg.rs, argmin/src/solver/particleswarm/mod.rs, argmin/src/solver/quasinewton/bfgs.rs, argmin/src/solver/quasinewton/dfp.rs, argmin/src/solver/quasinewton/lbfgs.rs, argmin/src/solver/quasinewton/mod.rs, argmin/src/solver/quasinewton/sr1.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs, argmin/src/tests.rs
=> Cleanup of Quasi-Newton methods

argmin/Cargo.toml
Before this commit it was necessary to include `argmin-math`, even if no backend such as `vec`, `ndarray` or `nalgebra` was used. Otherwise it would result in a compilation error. With this change it is only necessary to include `argmin-math` in the `Cargo.toml` if a backend is chosen.
=> Including argmin-math is now only necessary for choosing a backend

argmin/Cargo.toml, argmin/src/lib.rs, argmin/src/solver/gaussnewton/gaussnewton_linesearch.rs, argmin/src/solver/gaussnewton/gaussnewton_method.rs, argmin/src/solver/newton/newton_method.rs
Instead, users should choose the math backend via `argmin-math`. These features are unfortunately needed for running tests. In order to make it more clear that those are "internal" they are now prefixed by an underscore: `_ndarrayl` and `_nalgebral`.
Somewhat related to #227.
=> Features `ndarrayl` and `nalgebral` are not to be used by users

argmin/examples/sr1_trustregion.rs, argmin/examples/trustregion_nd.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs, argmin/src/solver/trustregion/cauchypoint.rs, argmin/src/solver/trustregion/dogleg.rs, argmin/src/solver/trustregion/mod.rs, argmin/src/solver/trustregion/steihaug.rs, argmin/src/solver/trustregion/trustregion_method.rs
=> Cleanup and improve documentation of trust region method, added doc and unit tests

.gitattributes
After adding the website, Github thinks that a large portion of the code is SCSS, HTML and JS files. These changes ignore that.
=> ignore website files for Languages graph in Github

argmin/examples/backtracking.rs, argmin/examples/bfgs.rs, argmin/examples/checkpoint.rs, argmin/examples/conjugategradient.rs, argmin/examples/dfp.rs, argmin/examples/hagerzhang.rs, argmin/examples/landweber.rs, argmin/examples/lbfgs.rs, argmin/examples/morethuente.rs, argmin/examples/newton_cg.rs, argmin/examples/nonlinear_cg.rs, argmin/examples/simulatedannealing.rs, argmin/examples/sr1.rs, argmin/examples/sr1_trustregion.rs, argmin/examples/steepestdescent.rs, argmin/examples/trustregion_nd.rs, argmin/examples/writers.rs
In code examples, both concrete type names and aliases are used for argument and return types of trait implementations.
This fix unifies the type name with aliases for consistency.
Also, return types of some gradient functions are incorrectly specified as `Param`, so this branch corrects them to `Gradient`.
=> Use alias type names in examples

argmin/src/solver/quasinewton/lbfgs.rs
According to Algorithm 1 in the OWL-QN paper, the $k$-th line search direction $p^k$ is calculated as follows:
$p^k \leftarrow \pi(d^k; v^k)$,
where $\pi_i(x_i; y_i)$ returns $x_i$ if $\sigma(x_i) = \sigma(y_i)$ and $0$ otherwise, $d^k = \boldsymbol{H_k} v^k$, and $v^k$ is a pseudo-gradient.
The current implementation calculates $p^k$ by filtering $d^k$ using the sign of the multiplication of $d^k$ and $v^k$.
However, this implementation returns a wrong result if $v^k_i = 0$ because $0$ has a sign in Rust.
For example, $\pi_i(-1.0; -0)$ must be $0$, but the current implementation returns $-1.0$.
This PR solves this problem by subtracting the minimum positive value from the multiplication of $d^k$ and $v^k$.
=> Fix π(x; y) in OWL-QN

.github/workflows/ci.yml, argmin-math/Cargo.toml, argmin-math/src/lib.rs, argmin-math/src/ndarray_m/mod.rs
Prior to version 0.6 the `ndarray-linalg` dependeny was optional to avoid having to link against non-rust libraries in builds which don't need to compute the matrix inverse. Somehow that got lost in 0.6 and causes problems downstream: https://github.com/rust-ml/linfa/pull/236 . This PR reintroduces this option in a way which hopefully is not a breaking change.
This causes problems with the dev-dependencies. Up until now, `ndarray-linalg` (v0.12, v0.13 and v0.14) were dev-dependencies because for testing/development one needs to select the blas backend. Now, for nolinalg builds, there is only the dev-dependency left and the build fails for some strange reason. To fix this, I have removed the dev dependencies and instead activate the blas backends via the `_dev_linalg` feature. This is …
=> Make ndarray-linalg dependency in argmin-math optional again

argmin/src/solver/quasinewton/lbfgs.rs
The pseudo-gradient of the next step must be calculated using the parameters of the next step, but the current implementation incorrectly uses the current parameters.
=> Fix calculating pseudo-gradient in OWL-QN

argmin/src/core/executor.rs, argmin/src/core/float.rs, argmin/src/core/kv.rs, argmin/src/core/macros.rs, argmin/src/core/mod.rs, argmin/src/core/observers/mod.rs, argmin/src/core/observers/slog_logger.rs, argmin/src/solver/conjugategradient/cg.rs, argmin/src/solver/conjugategradient/nonlinear_cg.rs, argmin/src/solver/neldermead/mod.rs, argmin/src/solver/quasinewton/lbfgs.rs, argmin/src/solver/quasinewton/sr1.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs, argmin/src/solver/simulatedannealing/mod.rs, argmin/src/solver/trustregion/trustregion_method.rs
This allows one to implement more powerful observers because the observed values are now directly available instead of just as a type which can be `Display`ed.
Internally `KV` is now a `HashMap` instead of a `Vec`. Furthermore a `get` method was added to be able to retrieve a value by key. 
The macro `make_kv!` was renamed to `kv!`.
A `keys` method was added to `KV` which returns the contained keys and their `KVType` kind.
=> Typed KV store

argmin/src/core/solver.rs
A result of the discussion in https://github.com/relf/egobox/issues/50 .
=> Remove unnecessary SerializeAlias trait bound on Solver

argmin-math/src/ndarray_m/mod.rs, argmin-math/src/ndarray_m/random.rs
Adds missing trait implementations for ndarray inputs.
=> Adding ndarray implementations for ArgminRandom and ArgminMinMax

argmin/src/core/solver.rs, media/book/src/implementing_solver.md
This PR changes slightly `terminate_internal` to use the best cost to check if the target cost is reached
instead of the current cost.
In the context of constrained optimization, the cost (the value of the cost function at the current
`param` vector) may be lower than the target cost but a constraint at this `param` vector may be violated.
In this case the target cost should not be declared to be reached.
The fix consists in using the best cost which is expected to be updated only if constraints are not violated.
=> Check if the target cost is reached using the best cost

argmin/src/core/executor.rs, argmin/src/core/termination.rs
Following discussion [here](https://github.com/argmin-rs/argmin/issues/305#issuecomment-1369137557), this PR implements the `KeyboardInterrupt` termination handling.
I've tested that it works properly with my solver.
As a follow-up discussion, I do not need the `finalize` method as initially I introduced it as a way to have a hook just at the end of the loop to check the `NotTerminated` and max iter not reached to detect keyboard interrupt like the existing check at the end of the `run` function.      
Now that `KeyboardInterrupt` is handled I think this last check to set `Aborted` is useless as well, as the state is always terminated, if you're ok I remove it.
=> Implement KeyboardInterrupt termination

argmin/src/core/executor.rs, argmin/src/core/mod.rs, argmin/src/core/result.rs, argmin/src/core/solver.rs, argmin/src/core/state/iterstate.rs, argmin/src/core/state/linearprogramstate.rs, argmin/src/core/state/mod.rs, argmin/src/core/state/populationstate.rs, argmin/src/core/termination.rs, argmin/src/solver/brent/brentopt.rs, argmin/src/solver/gaussnewton/gaussnewton_linesearch.rs, argmin/src/solver/gaussnewton/gaussnewton_method.rs, argmin/src/solver/goldensectionsearch/mod.rs, argmin/src/solver/linesearch/backtracking.rs, argmin/src/solver/linesearch/hagerzhang.rs, argmin/src/solver/neldermead/mod.rs, argmin/src/solver/newton/newton_cg.rs, argmin/src/solver/quasinewton/bfgs.rs, argmin/src/solver/quasinewton/dfp.rs, argmin/src/solver/quasinewton/lbfgs.rs, argmin/src/solver/quasinewton/sr1.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs, argmin/src/solver/simulatedannealing/mod.rs, argmin/src/solver/trustregion/cauchypoint.rs, argmin/src/solver/trustregion/dogleg.rs, argmin/src/solver/trustregion/steihaug.rs, argmin/src/solver/trustregion/trustregion_method.rs, media/book/src/running_solver.md
Following the discussion [here](https://github.com/argmin-rs/argmin/issues/305#issuecomment-1369137557), this PR implements `TerminationStatus`.
API changes:
* Added `TerminationStatus`
* Removed `NotTerminated` variant from `TerminationReason`
* Added in `State` trait: `get_termination_status()`
* Changed in `State` trait: `get_termination_reason()` returns an `Option<TerminationReason>`
=> Add TerminationStatus

.github/workflows/spellcheck.yml, CHANGELOG.md, README.md, _typos.toml, argmin/examples/backtracking.rs, argmin/examples/checkpoint.rs, argmin/examples/conjugategradient.rs, argmin/examples/hagerzhang.rs, argmin/examples/landweber.rs, argmin/examples/morethuente.rs, argmin/examples/nonlinear_cg.rs, argmin/examples/observer.rs, argmin/examples/trustregion_nd.rs, argmin/src/core/checkpointing/mod.rs, argmin/src/core/observers/slog_logger.rs, argmin/src/solver/quasinewton/sr1.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs, media/book/src/checkpointing.md, media/book/src/defining_optimization_problem.md, media/book/src/implementing_solver.md, media/book/src/observing.md, media/book/src/running_solver.md, media/book/src/using_argmin.md, media/website/config.toml, media/website/content/blog/version-v0.6.0.md, media/website/content/blog/version-v0.7.0.md
Well, that was a lot. I really don't know how to write "internal" and "initial".
=> Fixed typos and added spellcheck to CI

media/website/content/blog/sphrs_v0.2.0.md
https://github.com/argmin-rs/sphrs/releases/tag/v0.2.0
=> sphrs version 0.2.0 blog post

argmin/src/core/solver.rs, argmin/src/core/state/iterstate.rs, argmin/src/core/state/linearprogramstate.rs, argmin/src/core/state/mod.rs, argmin/src/core/state/populationstate.rs, argmin/src/core/termination.rs, argmin/src/solver/brent/brentopt.rs, argmin/src/solver/brent/brentroot.rs, argmin/src/solver/gaussnewton/gaussnewton_linesearch.rs, argmin/src/solver/gaussnewton/gaussnewton_method.rs, argmin/src/solver/goldensectionsearch/mod.rs, argmin/src/solver/linesearch/backtracking.rs, argmin/src/solver/linesearch/hagerzhang.rs, argmin/src/solver/linesearch/morethuente.rs, argmin/src/solver/neldermead/mod.rs, argmin/src/solver/newton/newton_cg.rs, argmin/src/solver/quasinewton/bfgs.rs, argmin/src/solver/quasinewton/dfp.rs, argmin/src/solver/quasinewton/lbfgs.rs, argmin/src/solver/quasinewton/sr1.rs, argmin/src/solver/quasinewton/sr1_trustregion.rs, argmin/src/solver/simulatedannealing/mod.rs, argmin/src/solver/trustregion/steihaug.rs
This PR implements a new version of `TerminationReason` enum as discussed  [here](https://github.com/argmin-rs/argmin/issues/305#issuecomment-1382015565).
It introduces the variant `SolverExit(String)` which allows to define custom stopping reason and `SolverConverged` which is intended to gather all successful exit reasons under the same umbrella. 
Some unwanted implementation consequences: 
* `TerminationReason` is not `Copy` anymore (`TerminationStatus` as well)
* We "loose" information when several successful exits are possible for a solver
=> New TerminationReason definition

README.md, argmin/src/lib.rs
@relf I'd like to mention egobox in the Readme and the docs in the hope that others will follow your example ;) Please let me know if you're for whatever reason not ok with that.
=> Mention egobox in docs and Readme

argmin-math/Cargo.toml, argmin-math/src/primitives/add.rs, argmin-math/src/primitives/conj.rs, argmin-math/src/primitives/div.rs, argmin-math/src/primitives/dot.rs, argmin-math/src/primitives/l1norm.rs, argmin-math/src/primitives/l2norm.rs, argmin-math/src/primitives/mul.rs, argmin-math/src/primitives/scaledadd.rs, argmin-math/src/primitives/scaledsub.rs, argmin-math/src/primitives/sub.rs, argmin-math/src/primitives/transpose.rs, argmin-math/src/primitives/weighteddot.rs, argmin-math/src/primitives/zero.rs, argmin-math/src/vec/add.rs, argmin-math/src/vec/div.rs, argmin-math/src/vec/dot.rs, argmin-math/src/vec/eye.rs, argmin-math/src/vec/l1norm.rs, argmin-math/src/vec/l2norm.rs, argmin-math/src/vec/minmax.rs, argmin-math/src/vec/mul.rs, argmin-math/src/vec/scaledadd.rs, argmin-math/src/vec/scaledsub.rs, argmin-math/src/vec/sub.rs, argmin-math/src/vec/transpose.rs, argmin-math/src/vec/zero.rs
Follows [(278)](https://github.com/argmin-rs/argmin/issues/278), changes every float equality check that gets run by `cargo test -p argmin-math`.
=> Replace `assert!` macros with macros from approx crate

argmin/src/core/observers/mod.rs
These impls got removed in 99f16b4d perhaps by accident I suppose. We've been using these impls in our project so I'd like to restore them.
=> Restore the Serialize/Deserialize impls for ObserverMode

argmin-math/src/ndarray_m/inv.rs
I tried to implement the f64/f32 standard inverse for the ArgminInv (modification in the implementation of inv for ndarray).
I also added a test for it.
For unknown compilation reasons on my machine (admittedly weird linux conf), I could not run the test nor use the library locally to check if that works. I will have to look later into it.
I am also not sure if this is what was needed (as a fully newcomer into rust).
**Short Update:** I could run the optimization for scalar function, it seems to work. I am not sure how to get the resulting `get_best_param` or `get_param` in the end, it seems that this function changed in 0.8.
=> Add trait f64 f32 for 1d inverse to ArgminInv

argmin/Cargo.toml, argmin/examples/steepestdescent.rs, argmin/examples/steepestdescent_manifold.rs, argmin/src/solver/gradientdescent/steepestdescent.rs, argmin/src/solver/linesearch/backtracking.rs, argmin/src/solver/linesearch/hagerzhang.rs, argmin/src/solver/linesearch/mod.rs, argmin/src/solver/linesearch/morethuente.rs
Previously, the line search operated directly over parameter space. This caused issues when there were different types for parameters vs gradients e.g. Lie Groups. This commit changes line searches to operate over gradient parameterization and incorporates gradient updates to parameters via ArgminScaledAdd.
I'm not sure sure what level of testing is needed for this but it passes all the unit tests with `cargo test` and I also ran the 3 line search examples and the steepest descent example
=> Correct line search to search over gradient

argmin/Cargo.toml, argmin/src/solver/conjugategradient/cg.rs, argmin/src/solver/linesearch/morethuente.rs, argmin/src/solver/particleswarm/mod.rs, media/book/src/contributing.md
In the docs, the `_dev_linalg_latest` feature which is needed to run the argmin-math tests with all backends was not mentioned.
=> Added missing feature for testing argmin-math (docs)

argmin-math/src/lib.rs, argmin-math/src/nalgebra_m/mod.rs, argmin-math/src/ndarray_m/mod.rs, argmin-math/src/primitives/mod.rs, argmin-math/src/vec/mod.rs
A strange one. Somehow couldn't find any useful information on this in the clippy repo.
=> Fixed clippy lints which complained about unused re-exports

CHANGELOG.md, README.md, argmin/Cargo.toml, media/book/src/README.md, media/book/src/using_argmin.md, media/website/content/blog/version-v0.9.0.md
Let's figure out again how to do a release!
=> argmin version 0.9.0

argmin/src/core/executor.rs, argmin/src/core/termination.rs, examples/timeout/Cargo.toml, examples/timeout/src/main.rs, media/book/src/running_solver.md
=> Add optional timeout to `Executor`

argmin/Cargo.toml, argmin/src/core/executor.rs, argmin/src/core/termination.rs
As suggested a while ago on [reddit](https://www.reddit.com/r/rust/comments/10o6jml/comment/j6cu80v/?utm_source=share&utm_medium=web2x&context=3). By adding the `termination` feature to `ctrlc`, we are able to capture SIGINT (Ctrl+C), SIGTERM and SIGHUP.
I changed `TerminationReason::KeyboardInterrupt` to `TerminationReason::Interrupt` to reflect that.
=> Interrupt handling now includes SIGINT, SIGTERM and SIGHUP, renamed `KeyboardInterrupt` to `Interrupt`

crates/argmin/src/solver/quasinewton/lbfgs.rs
=> Slightly better error handling in L-BFGS

crates/argmin/src/core/solver.rs, crates/argmin/src/tests.rs, python/argmin-testfunctions-py/.gitignore
In the tests there were still a few remnants of the times where
serialization and deserialization were more ingrained in the system.
This commit removes these remnants.
It also fixes a typo in the .gitignore file in argmin-testfunctions-py.
=> Removed unnecessary Serialize/Deserialize derives

crates/argmin-observer-paramwriter/Cargo.toml
Apparently one can't publish when a dev dependency doesn't have a
defined version.
=> Defined version for argmin-testfunctions dev dependency in paramwriter

README.md
The link pointed to the wrong (old) directory.
=> Fixed link to examples of latest release in README.md

crates/argmin/src/core/executor.rs, crates/argmin/src/core/state/iterstate.rs, crates/argmin/src/core/state/linearprogramstate.rs, crates/argmin/src/core/state/populationstate.rs, crates/argmin/src/solver/brent/brentopt.rs, crates/argmin/src/solver/linesearch/backtracking.rs, crates/argmin/src/tests.rs
- Add a benchmark (that works on stable toolchain) to establish the baseline
- Disable timing by default, enable when needed
- Disable execution counting by default
after:
```
newton  fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ run  4.9 µs        │ 171.4 µs      │ 5.25 µs       │ 6.218 µs      │ 4723907 │ 4723907
```
before:
```
newton  fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ run  6.317 µs      │ 171.8 µs      │ 6.729 µs      │ 7.75 µs       │ 3807698 │ 3807698
```
Fixes #482
=> Some minor optimizations

crates/argmin/Cargo.toml, crates/argmin/src/core/executor.rs, crates/argmin/src/core/state/iterstate.rs, crates/argmin/src/core/state/linearprogramstate.rs, crates/argmin/src/core/state/mod.rs, crates/argmin/src/core/state/populationstate.rs, deny.toml, examples/observer/Cargo.toml, examples/observer/src/main.rs
Fixes #538.
The changes are mostly trivial, mainly replacing `instant::Duration` with `web_time::Duration`.
I also made some small changes in the relevant doctests, using e.g. `Duration::ZERO` instead of `Duration::new(0, 0)` or `Duration::from_nanos(x)` instead of `Duration::new(0, x)`.
My understanding is that the equivalent of the `instant`'s `wasm-bindgen` feature [is always enabled](https://docs.rs/web-time/latest/web_time/#:~:text=wasm-bindgen) for `web-time`, though I didn't check what the CI checks on `wasm` targets.
=> Use web-time instead of unmaintained instant crate.

.github/workflows/ci.yml, deny.toml
As conversed about in PR #369, this PR removes the cargo-deny exclusion for intel-mkl-src introduced due to https://github.com/EmbarkStudios/krates/issues/60. 
This PR should be merged as soon as https://github.com/EmbarkStudios/krates/pull/61 lands in cargo-deny-action.
=> Remove cargo-deny exception for intel-mkl-src
