argmin-rs/argmin

README.md
Removes `work-in-progress` from README. See #26 for details.
=> Remove `work-in-progress` from README

src/solver/gaussnewton/gaussnewton_linesearch.rs, src/solver/gaussnewton/gaussnewton_method.rs
This exposes the stopping criterion tolerances of `GaussNewton` and `GaussNewtonLS` to the user. Related to #28.
=> Exposed stopping criterion tolerances of Gauss Newton methods to user

src/core/result.rs
Added `state()` and `operator()` methods to make the fields of `ArgminResult` more accessible to the user. Also added a bit of documentation about how to use the `state` field to access the relevant information. This is still not perfect, particularly the the name, as it may suggest that it has something to do with error handling. I'm open for suggestions :) See #32 for details.
This PR also stops deriving `Serialize` and `Deserialize` for `ArgminResult`, as it is not necessary and may be counterproductive when we finally remove the requirement that `ArgminOp` must implement `Serialize` and `Deserialize` (#7, #36).
=> Made `op` and `state` fields of `ArgminResult` more accessible

examples/goldensectionsearch.rs, src/solver/goldensectionsearch/mod.rs, src/solver/mod.rs
This is my first version of `Golden-section search`. I tested in our enterprise project and it's as good as my hardcoded version, but a little slower.
I know that there's no test, example, bench, nothing. I just want you to tell me what I did wrong. My own critic is that there's no way to choose the precision. If I understand correctly, everything is forced to f64 with `O: ArgminOp<Param = f64, Output = f64>,` so the user can't actually choose with
type Param = f32/f64;
type Output = f32/f64;
=> Golden-section search

src/lib.rs
Adds a link to the Golden-section search in the documentation.
=> Added Golden-section search to documentation

README.md
=> Added Golden-section search also to Readme

Cargo.toml, README.md, src/lib.rs
=> Release 0.3.0

src/solver/neldermead/mod.rs
=> remove unecessary Default bound on NelderMead

Cargo.toml, src/core/executor.rs, src/core/iterstate.rs, src/core/observers/visualizer.rs, src/lib.rs
=> Replace std::time with instant to work in wasm environment

Cargo.toml, examples/simulatedannealing.rs, src/core/math/inv_ndarray.rs, src/core/math/random_vec.rs
ndarray, ndarray-linalg, nalgebra, num-complex,rand, rand_xorshift, finitediff
=> Updated dependendies

Cargo.toml
=> bump to version 0.4.0

src/core/executor.rs, src/core/iterstate.rs, src/core/observers/mod.rs, src/core/serialization.rs
* eliminate calls to ArgminKV when there are no observers
* make the timer optional
* only create/append/destroy filename string when an iteration will write a checkpoint
See https://github.com/argmin-rs/argmin/issues/111 for more detail.
=> Performance Enhancements

Cargo.toml, README.md, src/lib.rs
=> update ndarray, ndarray-linalg, nalgebra, ndarray-rand, num-complex

CHANGELOG.md, Cargo.toml, README.md, src/core/executor.rs, src/core/iterstate.rs, src/core/mod.rs, src/core/observers/file.rs, src/core/observers/mod.rs, src/core/observers/visualizer.rs, src/core/termination.rs, src/lib.rs, src/solver/brent/mod.rs, src/solver/conjugategradient/beta.rs, src/solver/goldensectionsearch/mod.rs, src/solver/linesearch/morethuente.rs, src/solver/neldermead/mod.rs, src/solver/newton/newton_cg.rs, src/solver/quasinewton/lbfgs.rs, src/solver/trustregion/steihaug.rs
- Moved to Github actions (#130, @stefan-k)
- Updated README.md (#131, @stefan-k)
- Updated nalgebra from 0.28 to 0.29 (#133)
=> version 0.4.7

.github/workflows/ci.yml, src/core/executor.rs, src/core/math/dot_vec.rs, src/core/math/transpose_vec.rs
=> Correct check for new best parameter

src/solver/linesearch/backtracking.rs
This fixes an inconsistency between the state dependent values and the alpha value (which was one iteration ahead of the state) supplied to the line search condition in `Solver::terminate`.
I also removed the trait bounds `ArgminSub` and `ArgminDot` on the `Solver` impl as they were not used. I'm not sure if this was intentional.
See https://github.com/argmin-rs/argmin/issues/154.
=> Fix inconsistency between state and alpha value in Backtracking linesearch

src/solver/particleswarm/mod.rs
=> PSO: Corrected documentation, removed Hessian trait bounds

src/core/executor.rs
PR #152 introduced a bug which broke all solvers which do not compute the cost function value (such as Newtons Method). For those solvers, all cost function values are always `Inf`. With #152 new parameters had to have strictly smaller cost function values than the previous best to be accepted as the new best. Therefore, if all costs are `Inf`, no parameter will ever be accepted. This PR fixes this by treating infinity as special in the decision. Tests are included to prevent this from happening again.
=> Update best parameters when previous and current cost are Inf

src/solver/newton/newton_method.rs
Adds tests for the Newton method.
=> Tests for Newton method

README.md, src/lib.rs, src/solver/conjugategradient/cg.rs, src/solver/conjugategradient/nonlinear_cg.rs, src/solver/gaussnewton/gaussnewton_linesearch.rs, src/solver/gaussnewton/gaussnewton_method.rs, src/solver/gradientdescent/steepestdescent.rs, src/solver/landweber/mod.rs, src/solver/linesearch/backtracking.rs, src/solver/linesearch/hagerzhang.rs, src/solver/linesearch/morethuente.rs, src/solver/neldermead/mod.rs, src/solver/newton/newton_cg.rs, src/solver/newton/newton_method.rs, src/solver/particleswarm/mod.rs, src/solver/quasinewton/bfgs.rs, src/solver/quasinewton/dfp.rs, src/solver/quasinewton/lbfgs.rs, src/solver/quasinewton/sr1.rs, src/solver/quasinewton/sr1_trustregion.rs, src/solver/simulatedannealing/mod.rs, src/solver/trustregion/trustregion_method.rs
=> Remove links to examples in docs

argmin/src/solver/brent/mod.rs, argmin/src/solver/conjugategradient/cg.rs, argmin/src/solver/conjugategradient/mod.rs, argmin/src/solver/conjugategradient/nonlinear_cg.rs, argmin/src/solver/gaussnewton/gaussnewton_linesearch.rs, argmin/src/solver/gaussnewton/gaussnewton_method.rs, argmin/src/solver/gaussnewton/mod.rs
=> Cleanup and improve documentation of `GaussNewton` and `GaussNewtonLS`

argmin/examples/goldensectionsearch.rs, argmin/src/solver/goldensectionsearch/mod.rs
=> Improved documentation of `GoldenSectionSearch` and added tests

argmin/src/solver/gradientdescent/mod.rs, argmin/src/solver/gradientdescent/steepestdescent.rs, argmin/src/solver/linesearch/backtracking.rs, argmin/src/solver/linesearch/condition.rs
=> Improved documentation of `SteepestDescent` and added doc and unit tests

argmin/src/solver/landweber/mod.rs
=> Cleanup and improve documentation of `Landweber`, added doc and unit tests

argmin/src/solver/newton/mod.rs, argmin/src/solver/newton/newton_cg.rs, argmin/src/solver/newton/newton_method.rs
=> Cleanup and documentation of Newton method. Added doc and unit tests

argmin/Cargo.toml, argmin/examples/simulatedannealing.rs, argmin/src/core/kv.rs, argmin/src/solver/quasinewton/lbfgs.rs, argmin/src/solver/simulatedannealing/mod.rs
=> Cleanup and improve documentation of `SimulatedAnnealing`, added doc and unit tests

argmin/src/solver/trustregion/dogleg.rs, argmin/src/solver/trustregion/trustregion_method.rs
=> Fixed bug in Dogleg method

CHANGELOG.md, argmin-math/Cargo.toml, argmin/Cargo.toml, media/website/content/blog/version-v0.7.0.md
=> Release argmin v0.7.0 and argmin-math v0.2.0

media/book/src/using_argmin.md, media/website/config.toml, media/website/content/_index.md, media/website/content/blog/version-v0.6.0.md
Website and book now work with https. Also addresses #315.
=> Fixed link in book, moved from http to https

README.md, argmin/src/lib.rs
[Cobyla 0.3](https://github.com/relf/cobyla) joins the argmin solvers family.
=> Mention cobyla in docs and README

README.md
Change outdated link in the README
=> update latest release example link to v0.8.1

README.md, media/book/src/README.md
[Feel free to join!](https://discord.gg/fYB8AwxxMW)
=> Mention the new argmin Discord server

media/website/sass/bootstrap/package.json
Seems to work just as well without.
=> Remove vulnerable ip package from website
